const PAYMENT_STATUS = {
  CREATED: 'CREATED',
  PENDING: 'PENDING',
  SUCCESS: 'SUCCESS',
  FAILED: 'FAILED',
  REFUNDED: 'REFUNDED'
};

const BOOKING_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
  REFUNDED: 'REFUNDED'
};

const USER_ROLE = {
  USER: 'USER',
  ADMIN: 'ADMIN'
};

const PAYMENT_PURPOSE = {
  RENT: 'RENT',
  CREDIT_CARD: 'CREDIT_CARD',
  FLIGHT: 'FLIGHT',
  HOTEL: 'HOTEL',
  RECHARGE: 'RECHARGE',
  BILL: 'BILL'
};

module.exports = {
  PAYMENT_STATUS,
  BOOKING_STATUS,
  USER_ROLE,
  PAYMENT_PURPOSE
};
